### PR TITLE
Fix GPG key error

### LINKED ISSUE #58: gpg: keyserver receive failed: No data
Related issue : https://github.com/TheTorProject/ooni-web/issues/258

### PR DESCRIPTION
**Pull request by xhdix**
Close #58

### CODE REVIEW

**Comment by anadahz** [comment]
The Travis build errors due to GPG key issue, see pull request: https://github.com/ooni/probe-legacy/pull/57

**Comment by xhdix** [comment]
@anadahz Can you verify the changes?

**Comment by anadahz** [comment]
@xhdix I guess it's better to revert your changes.
Pull request (#57) is approved and should be merged soon.

**Comment by xhdix** [comment]
@anadahz OK, I have reverted the changes to the `.travis.yml` file.
Three other files still need to be modified. I'm not sure about the changes to the file `scripts/setup-dependencies.sh`.

**Comment by anadahz** [comment]
@xhdix #57 is merged. You can rebase your branch to the current master to resolve Travis errors.

**Comment by xhdix** [comment]
I think everything is right now.
@hellais @bassosimone  please review.

(I made the changes with the Atom editor so the extra spaces are automatically deleted)

**Comment by hellais** [comment]
LGTM

**Pull request merged**
